<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_- Use maximum 25 character_addressReg_9e23b3</name>
   <tag></tag>
   <elementGuidId>3a010896-69e9-4eed-abe3-cfe062de23f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;addressRegisterPage&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='addressRegisterPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ded4ca0b-384a-4386-bdf7-3c4d63185a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressRegisterPage</value>
      <webElementGuid>f870afed-bc68-4f40-89c0-dfd701223126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8caeccc5-d2ed-466a-8904-40c156858c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>secModel</value>
      <webElementGuid>c7e6d9cc-3cfe-482b-bc98-dfc408534336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-scope</value>
      <webElementGuid>8506b54b-be06-489f-8628-391f304c8b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formCover&quot;)/div[3]/div[@class=&quot;spliter&quot;]/sec-view[@class=&quot;ng-isolate-scope sec-view&quot;]/div[@class=&quot;inputContainer ng-scope&quot;]/input[@class=&quot;ng-pristine ng-untouched ng-valid ng-scope&quot;]</value>
      <webElementGuid>10d3c669-2ebd-489b-8b8f-7c53f2648b4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='addressRegisterPage']</value>
      <webElementGuid>7ea9c802-355b-42a4-9eb9-9bb631cceecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formCover']/div[3]/div[2]/sec-view/div/input</value>
      <webElementGuid>1098370d-f346-47a3-b4cd-03b48ae9eed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/sec-view/div/input</value>
      <webElementGuid>7d24bce3-5501-40c8-b132-70806997e1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'addressRegisterPage' and @type = 'text']</value>
      <webElementGuid>43c1bf0a-7811-4ff3-a487-b17fa5e44c6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
