<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_View Details</name>
   <tag></tag>
   <elementGuidId>b375a5ec-a678-41a6-85bf-80781c8cdb00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='details_10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#details_10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>07548ef2-80bd-4ee1-a032-93edbb901fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details_10</value>
      <webElementGuid>cff0c0eb-a9e4-40e3-8e11-38cc767c60d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop_nowSub viewDetail ng-scope</value>
      <webElementGuid>cccc7c0a-b923-463e-a932-33127c032757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>View_details</value>
      <webElementGuid>1ea7b4ca-68dc-49e8-ac01-2525ccb115f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Details</value>
      <webElementGuid>940136c3-bb99-44c0-ba04-aaa155051fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details_10&quot;)</value>
      <webElementGuid>fdf6d332-0143-4d02-958c-680713260286</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='details_10']</value>
      <webElementGuid>1c5e3641-712e-4fee-ac69-857a0124fcfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='popular_items']/div/div[2]/a/label</value>
      <webElementGuid>705fd915-b2a9-43b9-b490-dc35ece1ed63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[1]/following::label[1]</value>
      <webElementGuid>03a294a7-3b0c-4744-be7f-dbb54e8b2a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POPULAR ITEMS'])[2]/following::label[2]</value>
      <webElementGuid>5d78a4ad-1851-4963-a02c-2780ee846ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[3]/preceding::label[1]</value>
      <webElementGuid>5cffa907-d26e-4043-8341-ed932a005bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHAT WITH US'])[1]/preceding::label[2]</value>
      <webElementGuid>a2c71d81-098c-4313-8833-cb17637df674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/label</value>
      <webElementGuid>ff4683fc-516c-4638-8f9d-32424662f860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'details_10' and (text() = 'View Details' or . = 'View Details')]</value>
      <webElementGuid>04cc5f2f-88e6-4e41-acdf-1fc4a573778a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
